services:
  db:
    image: postgres:16-alpine
    container_name: fledu-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Server/Dockerfile
    container_name: fledu-api
    restart: always
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      API__BaseUrl: ${API_BASEURL}
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/wwwroot/uploads

volumes:
  pgdata:
